"""initial

Revision ID: 607668ad9b39
Revises:
Create Date: 2026-03-13 22:38:05.627975+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "607668ad9b39"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filters",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.String(length=64), nullable=False),
        sa.Column("min_rooms", sa.SmallInteger(), nullable=True),
        sa.Column("max_rooms", sa.SmallInteger(), nullable=True),
        sa.Column("min_sqm", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("max_sqm", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("min_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("max_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("social_status", sa.String(length=32), nullable=False),
        sa.Column("include_keywords", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("exclude_keywords", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_filters_chat_id"), "filters", ["chat_id"], unique=True)
    op.create_table(
        "listings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.String(length=255), nullable=False),
        sa.Column("source_slug", sa.String(length=64), nullable=False),
        sa.Column("source_name", sa.String(length=128), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rooms", sa.SmallInteger(), nullable=True),
        sa.Column("sqm", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("floor", sa.String(length=32), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("district", sa.String(length=128), nullable=True),
        sa.Column("social_status", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("published_at", sa.String(length=64), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_listings_first_seen", "listings", ["first_seen_at"], unique=False
    )
    op.create_index("idx_listings_notified", "listings", ["notified"], unique=False)
    op.create_index("idx_listings_price", "listings", ["price"], unique=False)
    op.create_index("idx_listings_rooms", "listings", ["rooms"], unique=False)
    op.create_index(
        "idx_listings_social_status", "listings", ["social_status"], unique=False
    )
    op.create_index("idx_listings_sqm", "listings", ["sqm"], unique=False)
    op.create_index(op.f("ix_listings_uid"), "listings", ["uid"], unique=False)
    op.create_index(
        "uq_listing", "listings", ["source_slug", "external_id"], unique=True
    )
    op.create_table(
        "scrape_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_slug", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("listings_found", sa.BigInteger(), nullable=False),
        sa.Column("new_listings", sa.BigInteger(), nullable=False),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_runs_source", "scrape_runs", ["source_slug", "started_at"], unique=False
    )
    op.create_table(
        "notification_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.String(length=64), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_notif_log_chat", "notification_log", ["chat_id"], unique=False)
    op.create_index(
        "idx_notif_log_listing", "notification_log", ["listing_id"], unique=False
    )
    op.create_index("idx_notif_log_sent", "notification_log", ["sent_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_notif_log_sent", table_name="notification_log")
    op.drop_index("idx_notif_log_listing", table_name="notification_log")
    op.drop_index("idx_notif_log_chat", table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_index("idx_runs_source", table_name="scrape_runs")
    op.drop_table("scrape_runs")
    op.drop_index("uq_listing", table_name="listings")
    op.drop_index(op.f("ix_listings_uid"), table_name="listings")
    op.drop_index("idx_listings_sqm", table_name="listings")
    op.drop_index("idx_listings_social_status", table_name="listings")
    op.drop_index("idx_listings_rooms", table_name="listings")
    op.drop_index("idx_listings_price", table_name="listings")
    op.drop_index("idx_listings_notified", table_name="listings")
    op.drop_index("idx_listings_first_seen", table_name="listings")
    op.drop_table("listings")
    op.drop_index(op.f("ix_filters_chat_id"), table_name="filters")
    op.drop_table("filters")
    # ### end Alembic commands ###
