"""initial1

Revision ID: 0a1fbfbc9f22
Revises: 607668ad9b39
Create Date: 2026-03-14 16:51:30.035936+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0a1fbfbc9f22"
down_revision: Union[str, Sequence[str], None] = "607668ad9b39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_notif_log_chat"), table_name="notification_log")
    op.drop_index(op.f("idx_notif_log_listing"), table_name="notification_log")
    op.drop_index(op.f("idx_notif_log_sent"), table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_index(op.f("idx_runs_source"), table_name="scrape_runs")
    op.drop_table("scrape_runs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scrape_runs",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "source_slug", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "finished_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("listings_found", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("new_listings", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("error_msg", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("success", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("scrape_runs_pkey")),
    )
    op.create_index(
        op.f("idx_runs_source"),
        "scrape_runs",
        ["source_slug", "started_at"],
        unique=False,
    )
    op.create_table(
        "notification_log",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "chat_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "sent_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("success", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("error_msg", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("notification_log_listing_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("notification_log_pkey")),
    )
    op.create_index(
        op.f("idx_notif_log_sent"), "notification_log", ["sent_at"], unique=False
    )
    op.create_index(
        op.f("idx_notif_log_listing"), "notification_log", ["listing_id"], unique=False
    )
    op.create_index(
        op.f("idx_notif_log_chat"), "notification_log", ["chat_id"], unique=False
    )
    # ### end Alembic commands ###
