"""initial

Revision ID: 233943f91b2e
Revises: 
Create Date: 2026-03-15 20:49:44.049661+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233943f91b2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('source_slug', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='EUR', nullable=False),
    sa.Column('rooms', sa.SmallInteger(), nullable=True),
    sa.Column('sqm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor', sa.SmallInteger(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('social_status', sa.String(length=32), server_default='any', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_stats', 'listings', ['source_slug', 'rooms', 'price', 'active'], unique=False)
    op.create_index(op.f('ix_listings_active'), 'listings', ['active'], unique=False)
    op.create_index(op.f('ix_listings_district'), 'listings', ['district'], unique=False)
    op.create_index(op.f('ix_listings_external_id'), 'listings', ['external_id'], unique=False)
    op.create_index(op.f('ix_listings_notified'), 'listings', ['notified'], unique=False)
    op.create_index(op.f('ix_listings_price'), 'listings', ['price'], unique=False)
    op.create_index(op.f('ix_listings_published_at'), 'listings', ['published_at'], unique=False)
    op.create_index(op.f('ix_listings_rooms'), 'listings', ['rooms'], unique=False)
    op.create_index(op.f('ix_listings_social_status'), 'listings', ['social_status'], unique=False)
    op.create_index(op.f('ix_listings_source_slug'), 'listings', ['source_slug'], unique=False)
    op.create_index(op.f('ix_listings_uid'), 'listings', ['uid'], unique=True)
    op.create_index('uq_listing_source_ext', 'listings', ['source_slug', 'external_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_chat_id'), 'users', ['chat_id'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('filters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('paused', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('min_rooms', sa.SmallInteger(), nullable=True),
    sa.Column('max_rooms', sa.SmallInteger(), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_sqm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_sqm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('social_status', sa.String(length=32), server_default='any', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['users.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_index(op.f('ix_filters_paused'), 'filters', ['paused'], unique=False)
    op.create_table('notified_listings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['users.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['listings.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notified_listings_chat_id'), 'notified_listings', ['chat_id'], unique=False)
    op.create_index(op.f('ix_notified_listings_uid'), 'notified_listings', ['uid'], unique=False)
    op.create_index('uq_notified_user_apt', 'notified_listings', ['uid', 'chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notified_user_apt', table_name='notified_listings')
    op.drop_index(op.f('ix_notified_listings_uid'), table_name='notified_listings')
    op.drop_index(op.f('ix_notified_listings_chat_id'), table_name='notified_listings')
    op.drop_table('notified_listings')
    op.drop_index(op.f('ix_filters_paused'), table_name='filters')
    op.drop_table('filters')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_chat_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_listing_source_ext', table_name='listings')
    op.drop_index(op.f('ix_listings_uid'), table_name='listings')
    op.drop_index(op.f('ix_listings_source_slug'), table_name='listings')
    op.drop_index(op.f('ix_listings_social_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_rooms'), table_name='listings')
    op.drop_index(op.f('ix_listings_published_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_price'), table_name='listings')
    op.drop_index(op.f('ix_listings_notified'), table_name='listings')
    op.drop_index(op.f('ix_listings_external_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_district'), table_name='listings')
    op.drop_index(op.f('ix_listings_active'), table_name='listings')
    op.drop_index('ix_listing_stats', table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
