"""initial

Revision ID: 52ad749421f4
Revises:
Create Date: 2026-03-20 20:41:53.692770+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "52ad749421f4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listing",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.String(length=255), nullable=False),
        sa.Column("source_slug", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "currency", sa.String(length=10), server_default="EUR", nullable=False
        ),
        sa.Column("rooms", sa.SmallInteger(), nullable=True),
        sa.Column("sqm", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("floor", sa.SmallInteger(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("district", sa.String(length=128), nullable=True),
        sa.Column(
            "social_status", sa.String(length=32), server_default="any", nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("notified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_listing_active"), "listing", ["active"], unique=False)
    op.create_index(op.f("ix_listing_district"), "listing", ["district"], unique=False)
    op.create_index(
        op.f("ix_listing_external_id"), "listing", ["external_id"], unique=False
    )
    op.create_index(op.f("ix_listing_notified"), "listing", ["notified"], unique=False)
    op.create_index(op.f("ix_listing_price"), "listing", ["price"], unique=False)
    op.create_index(
        op.f("ix_listing_published_at"), "listing", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_listing_rooms"), "listing", ["rooms"], unique=False)
    op.create_index(
        op.f("ix_listing_social_status"), "listing", ["social_status"], unique=False
    )
    op.create_index(
        op.f("ix_listing_source_slug"), "listing", ["source_slug"], unique=False
    )
    op.create_index(
        "ix_listing_stats",
        "listing",
        ["source_slug", "rooms", "price", "active"],
        unique=False,
    )
    op.create_index(op.f("ix_listing_uid"), "listing", ["uid"], unique=True)
    op.create_index(
        "uq_listing_source_ext", "listing", ["source_slug", "external_id"], unique=True
    )
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column(
            "language", sa.String(length=10), server_default="en", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_chat_id"), "user", ["chat_id"], unique=True)
    op.create_index(op.f("ix_user_is_active"), "user", ["is_active"], unique=False)
    op.create_table(
        "filter",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.String(length=64), nullable=False),
        sa.Column("paused", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("min_rooms", sa.SmallInteger(), nullable=True),
        sa.Column("max_rooms", sa.SmallInteger(), nullable=True),
        sa.Column("min_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("max_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("min_sqm", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("max_sqm", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column(
            "social_status", sa.String(length=32), server_default="any", nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["user.chat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id"),
    )
    op.create_index(op.f("ix_filter_paused"), "filter", ["paused"], unique=False)
    op.create_table(
        "notified_listing",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.String(length=255), nullable=False),
        sa.Column("chat_id", sa.String(length=64), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["user.chat_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uid"], ["listing.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notified_listing_chat_id"),
        "notified_listing",
        ["chat_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notified_listing_uid"), "notified_listing", ["uid"], unique=False
    )
    op.create_index(
        "uq_notified_user_apt", "notified_listing", ["uid", "chat_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_notified_user_apt", table_name="notified_listing")
    op.drop_index(op.f("ix_notified_listing_uid"), table_name="notified_listing")
    op.drop_index(op.f("ix_notified_listing_chat_id"), table_name="notified_listing")
    op.drop_table("notified_listing")
    op.drop_index(op.f("ix_filter_paused"), table_name="filter")
    op.drop_table("filter")
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.drop_index(op.f("ix_user_chat_id"), table_name="user")
    op.drop_table("user")
    op.drop_index("uq_listing_source_ext", table_name="listing")
    op.drop_index(op.f("ix_listing_uid"), table_name="listing")
    op.drop_index("ix_listing_stats", table_name="listing")
    op.drop_index(op.f("ix_listing_source_slug"), table_name="listing")
    op.drop_index(op.f("ix_listing_social_status"), table_name="listing")
    op.drop_index(op.f("ix_listing_rooms"), table_name="listing")
    op.drop_index(op.f("ix_listing_published_at"), table_name="listing")
    op.drop_index(op.f("ix_listing_price"), table_name="listing")
    op.drop_index(op.f("ix_listing_notified"), table_name="listing")
    op.drop_index(op.f("ix_listing_external_id"), table_name="listing")
    op.drop_index(op.f("ix_listing_district"), table_name="listing")
    op.drop_index(op.f("ix_listing_active"), table_name="listing")
    op.drop_table("listing")
    # ### end Alembic commands ###
